# Build prover-server
FROM golang:1.17-alpine as base

WORKDIR /build

RUN apk add --no-cache --update git

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY ./cmd ./cmd
COPY ./pkg ./pkg

RUN CGO_ENABLED=0 go build -o ./prover ./cmd/prover/prover.go


# Build rapidsnark
FROM ubuntu:20.04 as rapidsnark

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y curl build-essential libgmp-dev libsodium-dev nasm git cmake make m4 && rm -rf /var/lib/apt/lists/*

# rapidsnark
RUN mkdir /rapidsnark
WORKDIR /rapidsnark
RUN git clone https://github.com/0xPolygonID/rapidsnark.git ./
RUN git submodule init
RUN git submodule update
RUN ./build_gmp.sh host
RUN make host

# Main image
FROM node:16

ENV APP_USER=app
ENV APP_UID=1001

RUN apt-get update && apt-get install -y ca-certificates libsodium-dev libgomp1 && rm -rf /var/lib/apt/lists/*

RUN adduser -u $APP_UID $APP_USER --disabled-password --gecos "First Last,RoomNumber,WorkPhone,HomePhone"

ENV NPM_CONFIG_PREFIX=/home/app/node/.npm-global
RUN npm install -g snarkjs@latest

ENV PATH=${PATH}:/home/app/node/.npm-global/bin

COPY --from=base /build/prover /home/app/prover
#COPY --from=base /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# rapidsnark
COPY --from=rapidsnark /rapidsnark/package/bin/prover /usr/bin/rapidsnark

COPY ./configs/prover-rapidsnark.yaml   /home/app/configs/prover.yaml
COPY ./circuits  /home/app/circuits
COPY ./js        /home/app/js

RUN chown -R $APP_USER:$APP_USER /home/app

USER app:app
WORKDIR /home/app

# Command to run
ENTRYPOINT ["/home/app/prover"]

EXPOSE 8002
